version: '3'

services:
    testshop.db:
        container_name: '${PROJECT_NAME}.db'
        image: mysql/mysql-server:latest
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - testshop.mysql.data:/var/lib/mysql
            - ./../:/var/www/html
        networks:
            testshop_default:
                aliases:
                    - '${PROJECT_NAME}.db.host'

    testshop.php-fpm:
        container_name: '${PROJECT_NAME}.php-fpm'
        build:
            args:
                USER: ${CURRENT_USER}
                UID: ${CURRENT_UID}
                WORKING_DIR: ${WORKING_DIR}
            context: ./php-fpm
        depends_on:
            - '${PROJECT_NAME}.db'
        working_dir: ${WORKING_DIR}
        volumes:
            - ./../:${WORKING_DIR}
        networks:
            testshop_default:
                aliases:
                    - '${PROJECT_NAME}.php-fpm.host'

    testshop.nginx:
        container_name: '${PROJECT_NAME}.nginx'
        image: nginx:alpine
        volumes:
            - ./../:${WORKING_DIR}
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: ${WORKING_DIR}
        depends_on:
            - '${PROJECT_NAME}.php-fpm'
        ports:
            - ${NGINX_PORT}:80
        networks:
            testshop_default:
                aliases:
                    - '${PROJECT_NAME}.nginx.host'

volumes:
    testshop.mysql.data: ~

networks:
    testshop_default: ~
